version: '3.8'

services:
  db:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword # Em produção, recomenda-se utilizar Docker Secrets
      MARIADB_DATABASE: client_support
    volumes:
      - mariadbdata:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager # Fixado no manager caso utilize armazenamento persistente local do host
      restart_policy:
        condition: on-failure

  redis:
    image: redis:7-alpine
    volumes:
      - redisdata:/data
    deploy:
      placement:
        constraints:
          - node.role == manager # Mantém consistência e proximidade com o DB
      restart_policy:
        condition: on-failure

  backend:
    image: registry.advocase.site/client-support/backend:latest
    environment:
      - DATABASE_URL=root:rootpassword@tcp(db:3306)/client_support?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_URL=redis:6379
      - LOCAL_STORAGE_PATH=/app/storage
      - USE_S3=false
    volumes:
      - storage:/app/storage
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure

  app:
    image: registry.advocase.site/client-support/app:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure

volumes:
  mariadbdata:
  redisdata:
  storage:
