server:
  port: "8080"
database:
  url: "root:rootpassword@tcp(localhost:3306)/client_support?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  url: "localhost:6379"
jwt:
  secret: "my-secret-key-change-in-prod"
